/*

 ELEMENTS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define elementsBank 0

/* Super Gameboy palette 0 */
#define elementsSGBPal0c0 6076
#define elementsSGBPal0c1 8935
#define elementsSGBPal0c2 6596
#define elementsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define elementsSGBPal1c0 6076
#define elementsSGBPal1c1 8935
#define elementsSGBPal1c2 6596
#define elementsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define elementsSGBPal2c0 6076
#define elementsSGBPal2c1 8935
#define elementsSGBPal2c2 6596
#define elementsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define elementsSGBPal3c0 6076
#define elementsSGBPal3c1 8935
#define elementsSGBPal3c2 6596
#define elementsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define elementsCGBPal0c0 32767
#define elementsCGBPal0c1 6511
#define elementsCGBPal0c2 8592
#define elementsCGBPal0c3 10738

/* Gameboy Color palette 1 */
#define elementsCGBPal1c0 32767
#define elementsCGBPal1c1 4330
#define elementsCGBPal1c2 18724
#define elementsCGBPal1c3 22986

/* Gameboy Color palette 2 */
#define elementsCGBPal2c0 32767
#define elementsCGBPal2c1 4330
#define elementsCGBPal2c2 12016
#define elementsCGBPal2c3 20342

/* Gameboy Color palette 3 */
#define elementsCGBPal3c0 32767
#define elementsCGBPal3c1 4330
#define elementsCGBPal3c2 22161
#define elementsCGBPal3c3 27480

/* Gameboy Color palette 4 */
#define elementsCGBPal4c0 32767
#define elementsCGBPal4c1 4330
#define elementsCGBPal4c2 15599
#define elementsCGBPal4c3 31550

/* Gameboy Color palette 5 */
#define elementsCGBPal5c0 32767
#define elementsCGBPal5c1 4330
#define elementsCGBPal5c2 2133
#define elementsCGBPal5c3 5

/* Gameboy Color palette 6 */
#define elementsCGBPal6c0 32767
#define elementsCGBPal6c1 4330
#define elementsCGBPal6c2 169
#define elementsCGBPal6c3 10571

/* Gameboy Color palette 7 */
#define elementsCGBPal7c0 32767
#define elementsCGBPal7c1 4330
#define elementsCGBPal7c2 5529
#define elementsCGBPal7c3 10973

/* CGB palette entries. */
#define elementsCGB0 1
#define elementsCGB1 1
#define elementsCGB2 1
#define elementsCGB3 1
#define elementsCGB4 2
#define elementsCGB5 2
#define elementsCGB6 2
#define elementsCGB7 2
#define elementsCGB8 3
#define elementsCGB9 3
#define elementsCGB10 3
#define elementsCGB11 3
#define elementsCGB12 4
#define elementsCGB13 4
#define elementsCGB14 4
#define elementsCGB15 4
#define elementsCGB16 5
#define elementsCGB17 5
#define elementsCGB18 5
#define elementsCGB19 5
#define elementsCGB20 6
#define elementsCGB21 6
#define elementsCGB22 6
#define elementsCGB23 6
#define elementsCGB24 7
#define elementsCGB25 7
#define elementsCGB26 7
#define elementsCGB27 7
#define elementsCGB28 0
#define elementsCGB29 0
#define elementsCGB30 0
#define elementsCGB31 0
/* Start of tile array. */


/* End of ELEMENTS.H */
