/*

 INTERFACE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define interface_tilesBank 0

/* Super Gameboy palette 0 */
#define interface_tilesSGBPal0c0 6076
#define interface_tilesSGBPal0c1 8935
#define interface_tilesSGBPal0c2 6596
#define interface_tilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define interface_tilesSGBPal1c0 6076
#define interface_tilesSGBPal1c1 8935
#define interface_tilesSGBPal1c2 6596
#define interface_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define interface_tilesSGBPal2c0 6076
#define interface_tilesSGBPal2c1 8935
#define interface_tilesSGBPal2c2 6596
#define interface_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define interface_tilesSGBPal3c0 6076
#define interface_tilesSGBPal3c1 8935
#define interface_tilesSGBPal3c2 6596
#define interface_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define interface_tilesCGBPal0c0 32767
#define interface_tilesCGBPal0c1 20
#define interface_tilesCGBPal0c2 7398
#define interface_tilesCGBPal0c3 3171

/* Gameboy Color palette 1 */
#define interface_tilesCGBPal1c0 6076
#define interface_tilesCGBPal1c1 8935
#define interface_tilesCGBPal1c2 6596
#define interface_tilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define interface_tilesCGBPal2c0 6076
#define interface_tilesCGBPal2c1 8935
#define interface_tilesCGBPal2c2 6596
#define interface_tilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define interface_tilesCGBPal3c0 6076
#define interface_tilesCGBPal3c1 8935
#define interface_tilesCGBPal3c2 6596
#define interface_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define interface_tilesCGBPal4c0 6076
#define interface_tilesCGBPal4c1 8935
#define interface_tilesCGBPal4c2 6596
#define interface_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define interface_tilesCGBPal5c0 6076
#define interface_tilesCGBPal5c1 8935
#define interface_tilesCGBPal5c2 6596
#define interface_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define interface_tilesCGBPal6c0 6076
#define interface_tilesCGBPal6c1 8935
#define interface_tilesCGBPal6c2 6596
#define interface_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define interface_tilesCGBPal7c0 6076
#define interface_tilesCGBPal7c1 8935
#define interface_tilesCGBPal7c2 6596
#define interface_tilesCGBPal7c3 5344

/* CGB palette entries. */
#define interface_tilesCGB0 0
#define interface_tilesCGB1 0
#define interface_tilesCGB2 0
#define interface_tilesCGB3 0
#define interface_tilesCGB4 0
#define interface_tilesCGB5 0
#define interface_tilesCGB6 0
#define interface_tilesCGB7 0
#define interface_tilesCGB8 0
#define interface_tilesCGB9 0
#define interface_tilesCGB10 0
#define interface_tilesCGB11 0
#define interface_tilesCGB12 0
/* Start of tile array. */

/* End of INTERFACE_TILES.H */
