/*

 MAGICKA_PLAYER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 17

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define magicka_playerBank 0

/* Super Gameboy palette 0 */
#define magicka_playerSGBPal0c0 6076
#define magicka_playerSGBPal0c1 8935
#define magicka_playerSGBPal0c2 6596
#define magicka_playerSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define magicka_playerSGBPal1c0 6076
#define magicka_playerSGBPal1c1 8935
#define magicka_playerSGBPal1c2 6596
#define magicka_playerSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define magicka_playerSGBPal2c0 6076
#define magicka_playerSGBPal2c1 8935
#define magicka_playerSGBPal2c2 6596
#define magicka_playerSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define magicka_playerSGBPal3c0 6076
#define magicka_playerSGBPal3c1 8935
#define magicka_playerSGBPal3c2 6596
#define magicka_playerSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define magicka_playerCGBPal0c0 32767
#define magicka_playerCGBPal0c1 3871
#define magicka_playerCGBPal0c2 28
#define magicka_playerCGBPal0c3 0

/* Gameboy Color palette 1 */
#define magicka_playerCGBPal1c0 32767
#define magicka_playerCGBPal1c1 3871
#define magicka_playerCGBPal1c2 28
#define magicka_playerCGBPal1c3 1193

/* Gameboy Color palette 2 */
#define magicka_playerCGBPal2c0 32767
#define magicka_playerCGBPal2c1 3871
#define magicka_playerCGBPal2c2 28
#define magicka_playerCGBPal2c3 32527

/* Gameboy Color palette 3 */
#define magicka_playerCGBPal3c0 6076
#define magicka_playerCGBPal3c1 8935
#define magicka_playerCGBPal3c2 6596
#define magicka_playerCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define magicka_playerCGBPal4c0 6076
#define magicka_playerCGBPal4c1 8935
#define magicka_playerCGBPal4c2 6596
#define magicka_playerCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define magicka_playerCGBPal5c0 6076
#define magicka_playerCGBPal5c1 8935
#define magicka_playerCGBPal5c2 6596
#define magicka_playerCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define magicka_playerCGBPal6c0 6076
#define magicka_playerCGBPal6c1 8935
#define magicka_playerCGBPal6c2 6596
#define magicka_playerCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define magicka_playerCGBPal7c0 6076
#define magicka_playerCGBPal7c1 8935
#define magicka_playerCGBPal7c2 6596
#define magicka_playerCGBPal7c3 5344

/* CGB palette entries. */
#define magicka_playerCGB0 0
#define magicka_playerCGB1 2
#define magicka_playerCGB2 1
#define magicka_playerCGB3 0
#define magicka_playerCGB4 0
#define magicka_playerCGB5 2
#define magicka_playerCGB6 1
#define magicka_playerCGB7 0
#define magicka_playerCGB8 0
#define magicka_playerCGB9 2
#define magicka_playerCGB10 1
#define magicka_playerCGB11 0
#define magicka_playerCGB12 0
#define magicka_playerCGB13 2
#define magicka_playerCGB14 1
#define magicka_playerCGB15 1
#define magicka_playerCGB16 0
#define magicka_playerCGB17 0
/* Start of tile array. */

/* End of MAGICKA_PLAYER.H */
