/*

 TESTWORLDTILES_BW.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 26

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define testworldtiles_bwBank 0

/* Super Gameboy palette 0 */
#define testworldtiles_bwSGBPal0c0 6076
#define testworldtiles_bwSGBPal0c1 8935
#define testworldtiles_bwSGBPal0c2 6596
#define testworldtiles_bwSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define testworldtiles_bwSGBPal1c0 6076
#define testworldtiles_bwSGBPal1c1 8935
#define testworldtiles_bwSGBPal1c2 6596
#define testworldtiles_bwSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define testworldtiles_bwSGBPal2c0 6076
#define testworldtiles_bwSGBPal2c1 8935
#define testworldtiles_bwSGBPal2c2 6596
#define testworldtiles_bwSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define testworldtiles_bwSGBPal3c0 6076
#define testworldtiles_bwSGBPal3c1 8935
#define testworldtiles_bwSGBPal3c2 6596
#define testworldtiles_bwSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define testworldtiles_bwCGBPal0c0 29596
#define testworldtiles_bwCGBPal0c1 26425
#define testworldtiles_bwCGBPal0c2 15855
#define testworldtiles_bwCGBPal0c3 9513

/* Gameboy Color palette 1 */
#define testworldtiles_bwCGBPal1c0 32767
#define testworldtiles_bwCGBPal1c1 29596
#define testworldtiles_bwCGBPal1c2 26425
#define testworldtiles_bwCGBPal1c3 15855

/* Gameboy Color palette 2 */
#define testworldtiles_bwCGBPal2c0 23254
#define testworldtiles_bwCGBPal2c1 15855
#define testworldtiles_bwCGBPal2c2 9513
#define testworldtiles_bwCGBPal2c3 0

/* Gameboy Color palette 3 */
#define testworldtiles_bwCGBPal3c0 15855
#define testworldtiles_bwCGBPal3c1 6342
#define testworldtiles_bwCGBPal3c2 3171
#define testworldtiles_bwCGBPal3c3 0

/* Gameboy Color palette 4 */
#define testworldtiles_bwCGBPal4c0 15855
#define testworldtiles_bwCGBPal4c1 12684
#define testworldtiles_bwCGBPal4c2 9513
#define testworldtiles_bwCGBPal4c3 3171

/* Gameboy Color palette 5 */
#define testworldtiles_bwCGBPal5c0 32767
#define testworldtiles_bwCGBPal5c1 23254
#define testworldtiles_bwCGBPal5c2 13741
#define testworldtiles_bwCGBPal5c3 0

/* Gameboy Color palette 6 */
#define testworldtiles_bwCGBPal6c0 6502
#define testworldtiles_bwCGBPal6c1 3272
#define testworldtiles_bwCGBPal6c2 5541
#define testworldtiles_bwCGBPal6c3 9670

/* Gameboy Color palette 7 */
#define testworldtiles_bwCGBPal7c0 6076
#define testworldtiles_bwCGBPal7c1 8935
#define testworldtiles_bwCGBPal7c2 6596
#define testworldtiles_bwCGBPal7c3 5344

/* CGB palette entries. */
#define testworldtiles_bwCGB0 0
#define testworldtiles_bwCGB1 2
#define testworldtiles_bwCGB2 2
#define testworldtiles_bwCGB3 2
#define testworldtiles_bwCGB4 0
#define testworldtiles_bwCGB5 0
#define testworldtiles_bwCGB6 0
#define testworldtiles_bwCGB7 0
#define testworldtiles_bwCGB8 1
#define testworldtiles_bwCGB9 1
#define testworldtiles_bwCGB10 1
#define testworldtiles_bwCGB11 1
#define testworldtiles_bwCGB12 1
#define testworldtiles_bwCGB13 0
#define testworldtiles_bwCGB14 0
#define testworldtiles_bwCGB15 0
#define testworldtiles_bwCGB16 0
#define testworldtiles_bwCGB17 0
#define testworldtiles_bwCGB18 0
#define testworldtiles_bwCGB19 0
#define testworldtiles_bwCGB20 0
#define testworldtiles_bwCGB21 3
#define testworldtiles_bwCGB22 3
#define testworldtiles_bwCGB23 3
#define testworldtiles_bwCGB24 4
#define testworldtiles_bwCGB25 4
#define testworldtiles_bwCGB26 4
/* Start of tile array. */


/* End of TESTWORLDTILES_BW.H */
