/*

 TESTWORLDTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 26

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define testworldtilesBank 0

/* Super Gameboy palette 0 */
#define testworldtilesSGBPal0c0 6076
#define testworldtilesSGBPal0c1 8935
#define testworldtilesSGBPal0c2 6596
#define testworldtilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define testworldtilesSGBPal1c0 6076
#define testworldtilesSGBPal1c1 8935
#define testworldtilesSGBPal1c2 6596
#define testworldtilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define testworldtilesSGBPal2c0 6076
#define testworldtilesSGBPal2c1 8935
#define testworldtilesSGBPal2c2 6596
#define testworldtilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define testworldtilesSGBPal3c0 6076
#define testworldtilesSGBPal3c1 8935
#define testworldtilesSGBPal3c2 6596
#define testworldtilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define testworldtilesCGBPal0c0 17048
#define testworldtilesCGBPal0c1 12852
#define testworldtilesCGBPal0c2 7589
#define testworldtilesCGBPal0c3 6468

/* Gameboy Color palette 1 */
#define testworldtilesCGBPal1c0 18105
#define testworldtilesCGBPal1c1 17048
#define testworldtilesCGBPal1c2 12852
#define testworldtilesCGBPal1c3 7589

/* Gameboy Color palette 2 */
#define testworldtilesCGBPal2c0 9670
#define testworldtilesCGBPal2c1 7589
#define testworldtilesCGBPal2c2 6468
#define testworldtilesCGBPal2c3 2182

/* Gameboy Color palette 3 */
#define testworldtilesCGBPal3c0 7589
#define testworldtilesCGBPal3c1 3272
#define testworldtilesCGBPal3c2 2215
#define testworldtilesCGBPal3c3 2182

/* Gameboy Color palette 4 */
#define testworldtilesCGBPal4c0 7589
#define testworldtilesCGBPal4c1 5541
#define testworldtilesCGBPal4c2 4452
#define testworldtilesCGBPal4c3 3272

/* Gameboy Color palette 5 */
#define testworldtilesCGBPal5c0 32767
#define testworldtilesCGBPal5c1 23254
#define testworldtilesCGBPal5c2 13741
#define testworldtilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define testworldtilesCGBPal6c0 6502
#define testworldtilesCGBPal6c1 3272
#define testworldtilesCGBPal6c2 5541
#define testworldtilesCGBPal6c3 7589

/* Gameboy Color palette 7 */
#define testworldtilesCGBPal7c0 6076
#define testworldtilesCGBPal7c1 8935
#define testworldtilesCGBPal7c2 6596
#define testworldtilesCGBPal7c3 5344

/* CGB palette entries. */
#define testworldtilesCGB0 0
#define testworldtilesCGB1 2
#define testworldtilesCGB2 2
#define testworldtilesCGB3 2
#define testworldtilesCGB4 0
#define testworldtilesCGB5 0
#define testworldtilesCGB6 0
#define testworldtilesCGB7 0
#define testworldtilesCGB8 1
#define testworldtilesCGB9 1
#define testworldtilesCGB10 1
#define testworldtilesCGB11 1
#define testworldtilesCGB12 1
#define testworldtilesCGB13 0
#define testworldtilesCGB14 0
#define testworldtilesCGB15 0
#define testworldtilesCGB16 0
#define testworldtilesCGB17 0
#define testworldtilesCGB18 0
#define testworldtilesCGB19 0
#define testworldtilesCGB20 0
#define testworldtilesCGB21 3
#define testworldtilesCGB22 3
#define testworldtilesCGB23 3
#define testworldtilesCGB24 4
#define testworldtilesCGB25 4
#define testworldtilesCGB26 4
/* Start of tile array. */


/* End of TESTWORLDTILES.H */
